### ISSUE TITLE
Pac4JValueFactoryProvider.Binder() fails with NoClassDefFoundError when using Jersey 2.26

### ISSUE THREAD

**Issue by gbalkumar** [pac4j/jax-rs-pac4j#30]
The following code from the JAX-RS integration documentation fails when using Jersey 2.26 

`resourceConfig.register(new Pac4JValueFactoryProvider.Binder());
`

with the exception - 

```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/glassfish/jersey/server/internal/inject/AbstractContainerRequestValueFactory
	at org.pac4j.jax.rs.jersey.features.Pac4JValueFactoryProvider$Binder.<init>(Pac4JValueFactoryProvider.java:181)
	at org.pac4j.jax.rs.jersey.features.Pac4JValueFactoryProvider$Binder.<init>(Pac4JValueFactoryProvider.java:165)
	at com.techdata.vcp.config.Pac4JFeature.configure(Pac4JFeature.java:37)
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:701)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:635)
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:351)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:346)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:214)
```

Looks like AbstractContainerRequestValueFactory has been removed in Jersey 2.26 and [JERSEY #3630](https://github.com/jersey/jersey/issues/3630) suggests that implementations should not depend on internal.* packages.

**Comment by victornoel** [comment]
good point, I will look at it soon :)

**Comment by victornoel** [comment]
btw, be careful because jersey 2.26 is really a big breaking change release because they moved from jax-rs 2.0 to jax-rs 2.1.

I don't guarantee that jax-rs-pac4j works with jax-rs 2.1 (I didn't even try).

**Comment by gbalkumar** [comment]
Thanks. Except for that error, other things have been working fine so far with Jersey 2.26 although I will admit that my use-case so far is very basic.

**Comment by victornoel** [comment]
good to know, I will try to rewrite that code without the internal classes then!

**Comment by victornoel** [comment]
After some work, I arrived to the conclusion that we would need to rewrite the internal classes ourselves using hk2. So this means we would actually consider this new implementation to be an hk2-specific implementation and not a jersey-specific implementation.
That's not a problem per se, but that's a lot of work that would reproduce what Jersey was doing for us using the internal classes.

I'm not exactly sure where I should go with that actually, so I will keep this open, but I don't see this being done for now so you will have to keep using jersey 2.25.1 to get profile injection. Until then, you can get the `JaxRsContext` injected and build a `ProfileManager` from it.

This is a bit convoluted but this is how you do it:
```java
public class MyResource {
    @Context
    private Providers providers;

    @Inject
    private Provider<ContainerRequest> request;

    private JaxRsContext getContext() {
        return ProvidersHelper.getContext(providers, JaxRsContextFactory.class).provides(request.get());
    }
```

Honestly, JAX-RS and its main implementation Jersey promise a lot things, but they don't really deliver well with all that is related to customizing injection...

**Comment by pierre-l** [comment]
Hi, Github newbie here.

I think I have a decent solution, see the commit above. Tests are failing, I may have introduced a classpath issue there. I'm struggling to resolve this:

> javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: javax.ws.rs.core.Form

The Resteasy client doesn't seem to be able to find any writer. @victornoel, have you ever encountered this?
