### ISSUE TITLE
after start app,  high concurrence cause NullPointerException

### ISSUE THREAD

**Issue by lytccc** [pac4j/jax-rs-pac4j#479]
version resteasy5-pac4j 5.0.0

//pac4j config
```
DirectBasicAuthClient basicAuthClient = new DirectBasicAuthClient(new SimpleTestUsernamePasswordAuthenticator());
config = new Config("/callback", basicAuthClient);

```

// javax.ws.rs.Application
```
public class MyApp extends Application {
        @Override
        public Set<Object> getSingletons() {
            Config config = getConfig();
            Set<Object> singletons = new HashSet<>();
            singletons.add(new Pac4JServletFeature(config));
            singletons.add(new Pac4JSecurityFeature());
            return singletons;
        }

        @Override
        public Set<Class<?>> getClasses() {
            Set<Class<?>> classes = new HashSet<>();
            classes.add(ServletJaxRsContextFactoryProvider.class);
            classes.add(Pac4JProfileInjectorFactory.class);
            return classes;
        }
}

```

// rest resource
```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Pac4JSecurity(clients = "DirectBasicAuthClient")
    public UserData getUserData(@Pac4JProfile CommonProfile profile) {
        LOG.debug("Returning infos for {}", profile.getId());

        return new UserData(profile.getId(), profile.getDisplayName());
    }
```

// high concurrence request
`wrk -t100 -c2000 -d20s -H 'Authorization: Basic YTph' http://localhost:8080/`

**Comment by leleuj** [comment]
What NPE do you get?

**Comment by lytccc** [comment]
Caused by: java.lang.NullPointerException
	at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:71)
	at org.pac4j.http.client.direct.DirectBasicAuthClient.retrieveCredentials(DirectBasicAuthClient.java:51)
	at org.pac4j.core.client.DirectClient.getCredentials(DirectClient.java:44)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:108)
	at org.pac4j.jax.rs.filters.SecurityFilter.filter(SecurityFilter.java:58)
	at org.pac4j.jax.rs.filters.AbstractFilter.filter(AbstractFilter.java:47)

**Comment by leleuj** [comment]
This is quite strange.

In the pac4j config part, can you explicitly call `basicAuthClient.init();` and test again?

**Comment by lytccc** [comment]
basicAuthClient.init() is a remedy, no NullPointerException throw out.
But every clients (DirectBearerAuthClient.....) need init().

**Comment by leleuj** [comment]
Clients are lazzily initialized in pac4j but it looks like there is a problem here. Which version of pac4j do you have?

**Comment by lytccc** [comment]
version resteasy5-pac4j 5.0.0

**Comment by leleuj** [comment]
I meant the version of pac4j only (not reseteasy5-pac4j)? Like the `pac4j-core` dependency?

**Comment by lytccc** [comment]
5.7.1

**Comment by leleuj** [comment]
OK. Excellent. You are on the latest version.

To be honest, I don't understand why the client would be called without the `credentialsExtractor` properly initialized.

Can you test again after enabling DEBUG logs on: `org.pac4j.http.client.direct.DirectBasicAuthClient`, `org.pac4j.core.client.BaseClient` and `org.pac4j.core.util.InitializableObject`? Can you send me the logs up to the NPE: `jerome@casinthecloud.com`? Thx

**Comment by lytccc** [comment]
**no useful info**

......
Caused by: java.lang.NullPointerException
at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:71)
at org.pac4j.http.client.direct.DirectBasicAuthClient.retrieveCredentials(DirectBasicAuthClient.java:51)
at org.pac4j.core.client.DirectClient.getCredentials(DirectClient.java:44)
at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:108)
at org.pac4j.jax.rs.filters.SecurityFilter.filter(SecurityFilter.java:58)
at org.pac4j.jax.rs.filters.AbstractFilter.filter(AbstractFilter.java:47)
......
15:26:46 [XNIO-1 task-18] DEBUG o.p.h.c.d.DirectBasicAuthClient - credentials : #UsernamePasswordCredentials# | username: a | password: [PROTECTED] |
15:26:46 [XNIO-1 task-18] DEBUG o.p.h.c.d.DirectBasicAuthClient - profile: Optional[#CommonProfile# | id: a | attributes: {username=a} | authenticationAttributes: {} | roles: [] | permissions: [] | isRemembered: false | clientName: null | linkedId: null |]
15:26:46 [XNIO-1 task-112] DEBUG o.p.h.c.d.DirectBasicAuthClient - Credentials validation took: 0 ms

**Comment by lytccc** [comment]
**no useful info**


15:42:35 [XNIO-1 task-119] DEBUG o.p.core.util.InitializableObject - Initializing: Clients (nb: 0, last: null)
15:42:35 [XNIO-1 task-98] DEBUG o.p.core.util.InitializableObject - Initializing: DirectBasicAuthClient (nb: 0, last: null)

......
Caused by: java.lang.NullPointerException
at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:71)
at org.pac4j.http.client.direct.DirectBasicAuthClient.retrieveCredentials(DirectBasicAuthClient.java:51)
at org.pac4j.core.client.DirectClient.getCredentials(DirectClient.java:44)
at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:108)
at org.pac4j.jax.rs.filters.SecurityFilter.filter(SecurityFilter.java:58)
at org.pac4j.jax.rs.filters.AbstractFilter.filter(AbstractFilter.java:47)
......
15:26:46 [XNIO-1 task-18] DEBUG o.p.h.c.d.DirectBasicAuthClient - credentials : #UsernamePasswordCredentials# | username: a | password: [PROTECTED] |
15:26:46 [XNIO-1 task-18] DEBUG o.p.h.c.d.DirectBasicAuthClient - profile: Optional[#CommonProfile# | id: a | attributes: {username=a} | authenticationAttributes: {} | roles: [] | permissions: [] | isRemembered: false | clientName: null | linkedId: null |]
15:26:46 [XNIO-1 task-112] DEBUG o.p.h.c.d.DirectBasicAuthClient - Credentials validation took: 0 ms

**Comment by lytccc** [comment]
[app.log](https://github.com/pac4j/jax-rs-pac4j/files/13062665/app.log)

**Comment by leleuj** [comment]
You're fully right. That's not clearer. I don't understand what's going on: the client seems properly initialized but we get a NPE for line 71: `final var optCredentials = this.credentialsExtractor.extract(context, sessionStore);`, assuming the `credentialsExtractor` is `null`.

I just committed an explicit check of the nullity of the `credentialsExtractor`: https://github.com/pac4j/pac4j/commit/f3611e0c3ca63eb62a24841906c5d1dfe1df61d0

Can you switch to version 5.7.2-SNAPSHOT and test again? Just to confirm this is the right exception and that nothing is hidden.

The SNAPSHOT dependencies are in Sonatype:

```xml
<repositories>
  <repository>
    <id>sonatype-nexus-snapshots</id>
    <name>Sonatype Nexus Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by leleuj** [comment]
After the build is OK: https://github.com/pac4j/pac4j/actions/runs/6611202009

**Comment by lytccc** [comment]
new exception...

```
Caused by: org.pac4j.core.exception.TechnicalException: credentialsExtractor cannot be null
	at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:109)
	at org.pac4j.core.util.CommonHelper.assertNotNull(CommonHelper.java:141)
	at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:71)
	at org.pac4j.http.client.direct.DirectBasicAuthClient.retrieveCredentials(DirectBasicAuthClient.java:51)
	at org.pac4j.core.client.DirectClient.getCredentials(DirectClient.java:44)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:108)
	at org.pac4j.jax.rs.filters.SecurityFilter.filter(SecurityFilter.java:58)
	at org.pac4j.jax.rs.filters.AbstractFilter.filter(AbstractFilter.java:47)
```

**Comment by leleuj** [comment]
This is the expected exception. At least, this is what it seems to be.

I just add an explicit: `init()` before the `null`check: https://github.com/pac4j/pac4j/commit/e73588f09cc82aa7d3f26518d42c9e5476424e7a to try to understand what's going on.

Can you test again? Thx

**Comment by lytccc** [comment]
too
 org.pac4j.core.exception.TechnicalException: credentialsExtractor cannot be null

**Comment by leleuj** [comment]
Can you share your basic demo on some Github repository? Thanks
